kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    opendatahub.io/notebook-image-desc: >-
      Custom JupyterLab notebook image.
    opendatahub.io/notebook-image-name: Custom Notebook - Noah
    opendatahub.io/notebook-image-url: 'https://github.com/noahsa/odh-custom-notebook'
  name: custom-odh-notebook-noah
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      annotations:
        opendatahub.io/notebook-python-dependencies: >-
          [{"name":"Pytorch","version":"^1.10"}]
        opendatahub.io/notebook-software: '[{"name":"Custom Notebook Image - Noah","version":"1"},{"name":"Python","version":"3.9.2"}]'
      from:
        kind: DockerImage
        name: 'quay.io/nsayre/custom-notebook:latest'
      referencePolicy:
        type: Source